-- No-op: the explicit sip_trunks columns (realm, proxy, port, transport,
-- auth_username, auth_password_ciphertext, auth_password_key_id) were already
-- added by 0005_explicit_sip_trunk_fields.sql.  This file is intentionally
-- empty to preserve migration sequence numbering.
