-- Webhook event IDs and dead-letter queue enhancements.
--
-- 1. Idempotent event_id on every queued webhook delivery so consumers can
--    de-duplicate across retries. Generated by the API at enqueue time.
-- 2. DLQ metadata columns: abandoned_at, retry_count, dismiss_reason.

ALTER TABLE webhook_delivery_queue
    ADD COLUMN IF NOT EXISTS event_id uuid NOT NULL DEFAULT gen_random_uuid();

ALTER TABLE webhook_delivery_queue
    ADD COLUMN IF NOT EXISTS abandoned_at timestamptz;

ALTER TABLE webhook_delivery_queue
    ADD COLUMN IF NOT EXISTS dismissed_at timestamptz;

ALTER TABLE webhook_delivery_queue
    ADD COLUMN IF NOT EXISTS dismiss_reason text;

-- Partial unique index: only one non-dismissed delivery per (webhook, event_id).
CREATE UNIQUE INDEX IF NOT EXISTS webhook_delivery_queue_event_id_unique
    ON webhook_delivery_queue (webhook_id, event_id)
    WHERE dismissed_at IS NULL;

-- Fast DLQ query: abandoned items by tenant.
CREATE INDEX IF NOT EXISTS webhook_delivery_queue_abandoned_idx
    ON webhook_delivery_queue (tenant_id, abandoned_at DESC)
    WHERE status = 'abandoned' AND dismissed_at IS NULL;

ALTER TABLE webhook_delivery_log
    ADD COLUMN IF NOT EXISTS event_id uuid;
