export const ErrorCode = {
  NOT_FOUND: 'NOT_FOUND',
  INVALID_ARGUMENT: 'INVALID_ARGUMENT',
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  ALREADY_EXISTS: 'ALREADY_EXISTS',
  CONFLICT: 'CONFLICT',
  FAILED_PRECONDITION: 'FAILED_PRECONDITION',
  RESOURCE_EXHAUSTED: 'RESOURCE_EXHAUSTED',
  ENTITLEMENT_LIMIT_EXCEEDED: 'ENTITLEMENT_LIMIT_EXCEEDED',
  INTERNAL: 'INTERNAL',
  UNAVAILABLE: 'UNAVAILABLE',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
