import { useState } from 'react';
import { AlertTriangle, Bell, CheckCircle, XCircle, RefreshCcw } from 'lucide-react';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { PageHeader } from '@/components/layout/page-header';
import { DataCard } from '@/components/data/data-card';
import { Button } from '@/components/ui/button';
import {
  useSecurityAlerts,
  useAlertRules,
  useAcknowledgeAlert,
  useResolveAlert,
  useDismissAlert,
  useDeleteAlertRule,
  type SecurityAlertInstance,
  type SecurityAlertRule,
  type AlertInstanceStatus,
} from '@/lib/security-alerts/security-alerts-api';

const SEVERITY_CLASSES: Record<string, string> = {
  critical: 'bg-[var(--color-danger)]/10 text-[var(--color-danger)]',
  warning: 'bg-[var(--color-warning)]/10 text-[var(--color-warning)]',
  info: 'bg-[var(--color-info)]/10 text-[var(--color-info)]',
};

const STATUS_CLASSES: Record<string, string> = {
  new: 'bg-[var(--color-danger)]/10 text-[var(--color-danger)]',
  acknowledged: 'bg-[var(--color-warning)]/10 text-[var(--color-warning)]',
  resolved: 'bg-[var(--color-success)]/10 text-[var(--color-success)]',
  dismissed: 'bg-[var(--color-surface-muted)] text-[var(--color-muted-fg)]',
};

export function SecurityAlertsPage() {
  const qc = useQueryClient();
  const [statusFilter, setStatusFilter] = useState<AlertInstanceStatus | undefined>('new');
  const alertsQuery = useSecurityAlerts(statusFilter);
  const rulesQuery = useAlertRules();
  const acknowledge = useAcknowledgeAlert();
  const resolve = useResolveAlert();
  const dismiss = useDismissAlert();
  const deleteRule = useDeleteAlertRule();

  const refreshMutation = useMutation({
    mutationFn: async () => {
      await qc.invalidateQueries({ queryKey: ['security-alerts'] });
      await qc.invalidateQueries({ queryKey: ['security-alert-rules'] });
    },
  });

  return (
    <div className="space-y-6">
      <PageHeader
        eyebrow="Tenant Workspace"
        title="Security Alerts"
        description="Monitor and respond to telecom security events. Alerts are generated by active rules and reset after a cooldown period."
        actions={(
          <Button onClick={() => void refreshMutation.mutateAsync()} variant="secondary">
            <RefreshCcw className="size-4" aria-hidden="true" />
            Refresh
          </Button>
        )}
      />

      <div className="grid gap-6 xl:grid-cols-[1.5fr_0.75fr]">
        {/* Alert instances */}
        <DataCard
          title="Fired Alerts"
          description="Security events detected by active rules."
        >
          <div className="mb-3 flex flex-wrap gap-2">
            {(['new', 'acknowledged', 'resolved', 'dismissed', undefined] as const).map((s) => (
              <button
                key={s ?? 'all'}
                onClick={() => setStatusFilter(s)}
                className={[
                  'rounded-full px-3 py-1 text-xs font-medium transition-colors',
                  statusFilter === s
                    ? 'bg-[var(--color-tenant)] text-white'
                    : 'bg-[var(--color-surface-muted)] text-[var(--color-muted-fg)] hover:bg-[var(--color-border)]',
                ].join(' ')}
              >
                {s ?? 'All'}
              </button>
            ))}
          </div>

          {alertsQuery.isLoading ? (
            <p className="text-sm text-[var(--color-muted-fg)]">Loading alerts…</p>
          ) : alertsQuery.isError ? (
            <ErrorState message="Could not load security alerts." />
          ) : alertsQuery.data && alertsQuery.data.length > 0 ? (
            <div className="overflow-hidden rounded-[var(--radius-lg)] border border-[var(--color-border)]">
              <table className="w-full text-left text-sm">
                <thead className="bg-[var(--color-surface-muted)] text-[var(--color-muted-fg)]">
                  <tr>
                    <th className="px-3 py-2 font-medium">Severity</th>
                    <th className="px-3 py-2 font-medium">Type</th>
                    <th className="px-3 py-2 font-medium">Message</th>
                    <th className="px-3 py-2 font-medium">Status</th>
                    <th className="px-3 py-2 font-medium">Fired</th>
                    <th className="px-3 py-2 font-medium">Actions</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-[var(--color-border)] bg-[var(--color-surface)]">
                  {alertsQuery.data.map((alert) => (
                    <AlertRow
                      key={alert.id}
                      alert={alert}
                      onAcknowledge={() => void acknowledge.mutateAsync(alert.id)}
                      onResolve={() => void resolve.mutateAsync(alert.id)}
                      onDismiss={() => void dismiss.mutateAsync(alert.id)}
                      isPending={acknowledge.isPending || resolve.isPending || dismiss.isPending}
                    />
                  ))}
                </tbody>
              </table>
            </div>
          ) : (
            <EmptyState
              title="No alerts"
              description={statusFilter ? `No ${statusFilter} alerts found.` : 'No alerts found.'}
            />
          )}
        </DataCard>

        {/* Alert rules */}
        <DataCard
          title="Alert Rules"
          description="Active rules that generate security alerts."
        >
          {rulesQuery.isLoading ? (
            <p className="text-sm text-[var(--color-muted-fg)]">Loading rules…</p>
          ) : rulesQuery.isError ? (
            <ErrorState message="Could not load alert rules." />
          ) : rulesQuery.data && rulesQuery.data.length > 0 ? (
            <ul className="space-y-2">
              {rulesQuery.data.map((rule) => (
                <RuleRow
                  key={rule.id}
                  rule={rule}
                  onDelete={() => void deleteRule.mutateAsync(rule.id)}
                  isPending={deleteRule.isPending}
                />
              ))}
            </ul>
          ) : (
            <EmptyState
              title="No alert rules"
              description="Create alert rules via the API to start monitoring security events."
            />
          )}
        </DataCard>
      </div>
    </div>
  );
}

function AlertRow({
  alert,
  onAcknowledge,
  onResolve,
  onDismiss,
  isPending,
}: {
  alert: SecurityAlertInstance;
  onAcknowledge: () => void;
  onResolve: () => void;
  onDismiss: () => void;
  isPending: boolean;
}) {
  return (
    <tr>
      <td className="px-3 py-2">
        <Pill label={alert.severity} className={SEVERITY_CLASSES[alert.severity] ?? ''} />
      </td>
      <td className="px-3 py-2 font-mono text-xs text-[var(--color-muted-fg)]">
        {alert.alert_type.replace(/_/g, ' ')}
      </td>
      <td className="max-w-xs px-3 py-2 text-xs">{alert.message}</td>
      <td className="px-3 py-2">
        <Pill label={alert.status} className={STATUS_CLASSES[alert.status] ?? ''} />
      </td>
      <td className="px-3 py-2 text-xs text-[var(--color-muted-fg)]">
        {new Date(alert.fired_at).toLocaleString()}
      </td>
      <td className="px-3 py-2">
        <div className="flex gap-1">
          {alert.status === 'new' && (
            <Button
              variant="secondary"
              disabled={isPending}
              onClick={onAcknowledge}
              aria-label="Acknowledge"
            >
              <Bell className="size-3" aria-hidden="true" />
            </Button>
          )}
          {(alert.status === 'new' || alert.status === 'acknowledged') && (
            <Button
              disabled={isPending}
              onClick={onResolve}
              aria-label="Resolve"
            >
              <CheckCircle className="size-3" aria-hidden="true" />
            </Button>
          )}
          {alert.status !== 'resolved' && alert.status !== 'dismissed' && (
            <Button
              variant="secondary"
              disabled={isPending}
              onClick={onDismiss}
              aria-label="Dismiss"
            >
              <XCircle className="size-3" aria-hidden="true" />
            </Button>
          )}
        </div>
      </td>
    </tr>
  );
}

function RuleRow({
  rule,
  onDelete,
  isPending,
}: {
  rule: SecurityAlertRule;
  onDelete: () => void;
  isPending: boolean;
}) {
  return (
    <li className="flex items-start justify-between gap-2 rounded-[var(--radius-md)] border border-[var(--color-border)] bg-[var(--color-surface-muted)] px-3 py-2 text-sm">
      <div className="min-w-0">
        <div className="flex items-center gap-2">
          <AlertTriangle className="size-4 shrink-0 text-[var(--color-warning)]" aria-hidden="true" />
          <p className="truncate font-medium">{rule.name}</p>
          <Pill label={rule.severity} className={SEVERITY_CLASSES[rule.severity] ?? ''} />
        </div>
        <p className="mt-0.5 font-mono text-xs text-[var(--color-muted-fg)]">
          {rule.alert_type.replace(/_/g, ' ')} · {rule.status}
        </p>
      </div>
      <Button
        variant="secondary"
        disabled={isPending}
        onClick={onDelete}
        aria-label={`Delete rule ${rule.name}`}
      >
        <XCircle className="size-3" aria-hidden="true" />
      </Button>
    </li>
  );
}

function Pill({ label, className }: { label: string; className: string }) {
  return (
    <span className={`inline-flex items-center rounded-full px-2 py-0.5 text-xs font-medium ${className}`}>
      {label}
    </span>
  );
}

function EmptyState({ title, description }: { title: string; description: string }) {
  return (
    <div className="rounded-[var(--radius-lg)] bg-[var(--color-surface-muted)] px-4 py-6 text-sm text-[var(--color-muted-fg)]">
      <p className="font-medium text-[var(--color-fg)]">{title}</p>
      <p className="mt-2">{description}</p>
    </div>
  );
}

function ErrorState({ message }: { message: string }) {
  return (
    <div className="rounded-[var(--radius-lg)] border border-[var(--color-danger)]/20 bg-[var(--color-danger)]/10 px-4 py-6 text-sm text-[var(--color-danger)]">
      {message}
    </div>
  );
}
