export type Role = 'platform_admin' | 'tenant_admin' | 'tenant_operator' | 'tenant_viewer';

export const CAPABILITIES = {
  PLATFORM_TENANTS_VIEW: 'platform.tenants.view',
  PLATFORM_RUNTIME_VIEW: 'platform.runtime.view',
  PLATFORM_AUDIT_VIEW: 'platform.audit.view',

  TENANT_DASHBOARD_VIEW: 'tenant.dashboard.view',
  TENANT_EXTENSIONS_VIEW: 'tenant.extensions.view',
  TENANT_EXTENSIONS_CREATE: 'tenant.extensions.create',
  TENANT_EXTENSIONS_UPDATE: 'tenant.extensions.update',
  TENANT_EXTENSIONS_DEACTIVATE: 'tenant.extensions.deactivate',
  TENANT_CALLS_VIEW: 'tenant.calls.view',
  TENANT_DIRECTORY_SMOKE_TEST: 'tenant.directory_smoke_test.run',

  TENANT_PHONE_NUMBERS_VIEW: 'tenant.phone_numbers.view',
  TENANT_PHONE_NUMBERS_CREATE: 'tenant.phone_numbers.create',
  TENANT_PHONE_NUMBERS_UPDATE: 'tenant.phone_numbers.update',
  TENANT_PHONE_NUMBERS_DEACTIVATE: 'tenant.phone_numbers.deactivate',

  TENANT_INBOUND_ROUTES_VIEW: 'tenant.inbound_routes.view',
  TENANT_INBOUND_ROUTES_CREATE: 'tenant.inbound_routes.create',
  TENANT_INBOUND_ROUTES_UPDATE: 'tenant.inbound_routes.update',
  TENANT_INBOUND_ROUTES_ACTIVATE: 'tenant.inbound_routes.activate',
  TENANT_INBOUND_ROUTES_DEACTIVATE: 'tenant.inbound_routes.deactivate',
  TENANT_INBOUND_ROUTES_TEST: 'tenant.inbound_routes.test',

  TENANT_IVR_FLOWS_VIEW: 'tenant.ivr_flows.view',
  TENANT_IVR_FLOWS_CREATE: 'tenant.ivr_flows.create',
  TENANT_IVR_FLOWS_UPDATE: 'tenant.ivr_flows.update',
  TENANT_IVR_FLOWS_VALIDATE: 'tenant.ivr_flows.validate',
  TENANT_IVR_FLOWS_SIMULATE: 'tenant.ivr_flows.simulate',
  TENANT_IVR_FLOWS_PUBLISH: 'tenant.ivr_flows.publish',
  TENANT_IVR_FLOWS_ROLLBACK: 'tenant.ivr_flows.rollback',

  TENANT_PROMPTS_VIEW: 'tenant.prompts.view',
  TENANT_PROMPTS_CREATE: 'tenant.prompts.create',
  TENANT_PROMPTS_DEACTIVATE: 'tenant.prompts.deactivate',

  TENANT_APPROVALS_VIEW: 'tenant.approvals.view',
  TENANT_APPROVALS_DECIDE: 'tenant.approvals.decide',

  TENANT_QUEUES_VIEW: 'tenant.queues.view',
  TENANT_QUEUES_CREATE: 'tenant.queues.create',
  TENANT_QUEUES_UPDATE: 'tenant.queues.update',
  TENANT_QUEUES_DEACTIVATE: 'tenant.queues.deactivate',

  TENANT_VOICEMAIL_BOXES_VIEW: 'tenant.voicemail_boxes.view',
  TENANT_VOICEMAIL_BOXES_CREATE: 'tenant.voicemail_boxes.create',
  TENANT_VOICEMAIL_BOXES_UPDATE: 'tenant.voicemail_boxes.update',
  TENANT_VOICEMAIL_BOXES_DEACTIVATE: 'tenant.voicemail_boxes.deactivate',

  TENANT_AUTOMATION_WEBHOOKS_VIEW: 'tenant.automation.webhooks.view',
  TENANT_AUTOMATION_WEBHOOKS_MANAGE: 'tenant.automation.webhooks.manage',

  TENANT_SCHEDULES_VIEW: 'tenant.schedules.view',
  TENANT_SCHEDULES_CREATE: 'tenant.schedules.create',
  TENANT_SCHEDULES_UPDATE: 'tenant.schedules.update',

  TENANT_OUTBOUND_ROUTES_VIEW: 'tenant.outbound_routes.view',
  TENANT_OUTBOUND_ROUTES_CREATE: 'tenant.outbound_routes.create',
  TENANT_OUTBOUND_ROUTES_UPDATE: 'tenant.outbound_routes.update',

  TENANT_OUTBOUND_CALLS_CREATE: 'tenant.outbound_calls.create',
  TENANT_OUTBOUND_CALLS_VIEW: 'tenant.outbound_calls.view',

  TENANT_CHANNEL_ACCOUNTS_VIEW: 'tenant.channel_accounts.view',
  TENANT_CHANNEL_ACCOUNTS_MANAGE: 'tenant.channel_accounts.manage',
  TENANT_CHANNEL_MESSAGES_VIEW: 'tenant.channel_messages.view',
  TENANT_CHANNEL_MESSAGES_SEND: 'tenant.channel_messages.send',
  TENANT_MEETING_SESSIONS_VIEW: 'tenant.meeting_sessions.view',
  TENANT_MEETING_SESSIONS_MANAGE: 'tenant.meeting_sessions.manage',

  TENANT_AUDIT_LOG_VIEW: 'tenant.audit_log.view',

  TENANT_RECORDINGS_VIEW: 'tenant.recordings.view',
  TENANT_EXPORT_RUN: 'tenant.export.run',

  TENANT_USERS_VIEW: 'tenant.users.view',
  TENANT_USERS_MANAGE: 'tenant.users.manage',
} as const;

export type Capability = (typeof CAPABILITIES)[keyof typeof CAPABILITIES];

const TENANT_VIEW_CAPABILITIES: readonly Capability[] = [
  CAPABILITIES.TENANT_DASHBOARD_VIEW,
  CAPABILITIES.TENANT_EXTENSIONS_VIEW,
  CAPABILITIES.TENANT_CALLS_VIEW,
  CAPABILITIES.TENANT_RECORDINGS_VIEW,
  CAPABILITIES.TENANT_PHONE_NUMBERS_VIEW,
  CAPABILITIES.TENANT_INBOUND_ROUTES_VIEW,
  CAPABILITIES.TENANT_PROMPTS_VIEW,
  CAPABILITIES.TENANT_IVR_FLOWS_VIEW,
  CAPABILITIES.TENANT_APPROVALS_VIEW,
  CAPABILITIES.TENANT_QUEUES_VIEW,
  CAPABILITIES.TENANT_VOICEMAIL_BOXES_VIEW,
  CAPABILITIES.TENANT_AUTOMATION_WEBHOOKS_VIEW,
  CAPABILITIES.TENANT_SCHEDULES_VIEW,
  CAPABILITIES.TENANT_OUTBOUND_ROUTES_VIEW,
  CAPABILITIES.TENANT_OUTBOUND_CALLS_VIEW,
  CAPABILITIES.TENANT_CHANNEL_ACCOUNTS_VIEW,
  CAPABILITIES.TENANT_CHANNEL_MESSAGES_VIEW,
  CAPABILITIES.TENANT_MEETING_SESSIONS_VIEW,
];

const TENANT_OPERATOR_CAPABILITIES: readonly Capability[] = [
  ...TENANT_VIEW_CAPABILITIES,
  CAPABILITIES.TENANT_AUDIT_LOG_VIEW,
  CAPABILITIES.TENANT_EXPORT_RUN,
  CAPABILITIES.TENANT_USERS_VIEW,
  CAPABILITIES.TENANT_DIRECTORY_SMOKE_TEST,
  CAPABILITIES.TENANT_EXTENSIONS_CREATE,
  CAPABILITIES.TENANT_EXTENSIONS_UPDATE,
  CAPABILITIES.TENANT_PHONE_NUMBERS_CREATE,
  CAPABILITIES.TENANT_PHONE_NUMBERS_UPDATE,
  CAPABILITIES.TENANT_INBOUND_ROUTES_CREATE,
  CAPABILITIES.TENANT_INBOUND_ROUTES_UPDATE,
  CAPABILITIES.TENANT_INBOUND_ROUTES_ACTIVATE,
  CAPABILITIES.TENANT_INBOUND_ROUTES_TEST,
  CAPABILITIES.TENANT_PROMPTS_CREATE,
  CAPABILITIES.TENANT_IVR_FLOWS_CREATE,
  CAPABILITIES.TENANT_IVR_FLOWS_UPDATE,
  CAPABILITIES.TENANT_IVR_FLOWS_VALIDATE,
  CAPABILITIES.TENANT_IVR_FLOWS_SIMULATE,
  CAPABILITIES.TENANT_QUEUES_CREATE,
  CAPABILITIES.TENANT_QUEUES_UPDATE,
  CAPABILITIES.TENANT_VOICEMAIL_BOXES_CREATE,
  CAPABILITIES.TENANT_VOICEMAIL_BOXES_UPDATE,
  CAPABILITIES.TENANT_SCHEDULES_CREATE,
  CAPABILITIES.TENANT_SCHEDULES_UPDATE,
  CAPABILITIES.TENANT_OUTBOUND_ROUTES_CREATE,
  CAPABILITIES.TENANT_OUTBOUND_ROUTES_UPDATE,
  CAPABILITIES.TENANT_OUTBOUND_CALLS_CREATE,
  CAPABILITIES.TENANT_CHANNEL_ACCOUNTS_MANAGE,
  CAPABILITIES.TENANT_CHANNEL_MESSAGES_SEND,
  CAPABILITIES.TENANT_MEETING_SESSIONS_MANAGE,
];

const TENANT_CAPABILITIES: readonly Capability[] = [
  ...TENANT_OPERATOR_CAPABILITIES,
  CAPABILITIES.TENANT_EXTENSIONS_DEACTIVATE,
  CAPABILITIES.TENANT_PHONE_NUMBERS_DEACTIVATE,
  CAPABILITIES.TENANT_INBOUND_ROUTES_DEACTIVATE,
  CAPABILITIES.TENANT_PROMPTS_DEACTIVATE,
  CAPABILITIES.TENANT_IVR_FLOWS_PUBLISH,
  CAPABILITIES.TENANT_IVR_FLOWS_ROLLBACK,
  CAPABILITIES.TENANT_APPROVALS_DECIDE,
  CAPABILITIES.TENANT_QUEUES_DEACTIVATE,
  CAPABILITIES.TENANT_VOICEMAIL_BOXES_DEACTIVATE,
  CAPABILITIES.TENANT_AUTOMATION_WEBHOOKS_MANAGE,
  CAPABILITIES.TENANT_USERS_MANAGE,
];

const ROLE_CAPABILITIES: Record<Role, readonly Capability[]> = {
  platform_admin: [
    CAPABILITIES.PLATFORM_TENANTS_VIEW,
    CAPABILITIES.PLATFORM_RUNTIME_VIEW,
    CAPABILITIES.PLATFORM_AUDIT_VIEW,
    ...TENANT_CAPABILITIES,
  ],
  tenant_admin: TENANT_CAPABILITIES,
  tenant_operator: TENANT_OPERATOR_CAPABILITIES,
  tenant_viewer: TENANT_VIEW_CAPABILITIES,
};

export function hasCapability(role: Role | string | undefined, capability: Capability): boolean {
  if (!role || !(role in ROLE_CAPABILITIES)) return false;
  return (ROLE_CAPABILITIES[role as Role] as readonly string[]).includes(capability);
}
