export type Role = 'platform_admin' | 'tenant_admin';

export const CAPABILITIES = {
  PLATFORM_TENANTS_VIEW: 'platform.tenants.view',
  PLATFORM_RUNTIME_VIEW: 'platform.runtime.view',
  PLATFORM_AUDIT_VIEW: 'platform.audit.view',

  TENANT_DASHBOARD_VIEW: 'tenant.dashboard.view',
  TENANT_EXTENSIONS_VIEW: 'tenant.extensions.view',
  TENANT_EXTENSIONS_CREATE: 'tenant.extensions.create',
  TENANT_EXTENSIONS_UPDATE: 'tenant.extensions.update',
  TENANT_EXTENSIONS_DEACTIVATE: 'tenant.extensions.deactivate',
  TENANT_CALLS_VIEW: 'tenant.calls.view',
  TENANT_DIRECTORY_SMOKE_TEST: 'tenant.directory_smoke_test.run',
  TENANT_IVR_FLOWS_VIEW: 'tenant.ivr_flows.view',
  TENANT_IVR_FLOWS_CREATE: 'tenant.ivr_flows.create',
  TENANT_IVR_FLOWS_UPDATE: 'tenant.ivr_flows.update',
  TENANT_IVR_FLOWS_VALIDATE: 'tenant.ivr_flows.validate',
  TENANT_IVR_FLOWS_SIMULATE: 'tenant.ivr_flows.simulate',
  TENANT_IVR_FLOWS_PUBLISH: 'tenant.ivr_flows.publish',
  TENANT_IVR_FLOWS_ROLLBACK: 'tenant.ivr_flows.rollback',
} as const;

export type Capability = (typeof CAPABILITIES)[keyof typeof CAPABILITIES];

const ROLE_CAPABILITIES: Record<Role, readonly Capability[]> = {
  platform_admin: [
    CAPABILITIES.PLATFORM_TENANTS_VIEW,
    CAPABILITIES.PLATFORM_RUNTIME_VIEW,
    CAPABILITIES.PLATFORM_AUDIT_VIEW,
    CAPABILITIES.TENANT_DASHBOARD_VIEW,
    CAPABILITIES.TENANT_EXTENSIONS_VIEW,
    CAPABILITIES.TENANT_EXTENSIONS_CREATE,
    CAPABILITIES.TENANT_EXTENSIONS_UPDATE,
    CAPABILITIES.TENANT_EXTENSIONS_DEACTIVATE,
    CAPABILITIES.TENANT_CALLS_VIEW,
    CAPABILITIES.TENANT_DIRECTORY_SMOKE_TEST,
    CAPABILITIES.TENANT_IVR_FLOWS_VIEW,
    CAPABILITIES.TENANT_IVR_FLOWS_CREATE,
    CAPABILITIES.TENANT_IVR_FLOWS_UPDATE,
    CAPABILITIES.TENANT_IVR_FLOWS_VALIDATE,
    CAPABILITIES.TENANT_IVR_FLOWS_SIMULATE,
    CAPABILITIES.TENANT_IVR_FLOWS_PUBLISH,
    CAPABILITIES.TENANT_IVR_FLOWS_ROLLBACK,
  ],
  tenant_admin: [
    CAPABILITIES.TENANT_DASHBOARD_VIEW,
    CAPABILITIES.TENANT_EXTENSIONS_VIEW,
    CAPABILITIES.TENANT_EXTENSIONS_CREATE,
    CAPABILITIES.TENANT_EXTENSIONS_UPDATE,
    CAPABILITIES.TENANT_EXTENSIONS_DEACTIVATE,
    CAPABILITIES.TENANT_CALLS_VIEW,
    CAPABILITIES.TENANT_DIRECTORY_SMOKE_TEST,
    CAPABILITIES.TENANT_IVR_FLOWS_VIEW,
    CAPABILITIES.TENANT_IVR_FLOWS_CREATE,
    CAPABILITIES.TENANT_IVR_FLOWS_UPDATE,
    CAPABILITIES.TENANT_IVR_FLOWS_VALIDATE,
    CAPABILITIES.TENANT_IVR_FLOWS_SIMULATE,
    CAPABILITIES.TENANT_IVR_FLOWS_PUBLISH,
    CAPABILITIES.TENANT_IVR_FLOWS_ROLLBACK,
  ],
};

export function hasCapability(role: Role | undefined, capability: Capability): boolean {
  const effectiveRole: Role = role ?? 'tenant_admin';
  return (ROLE_CAPABILITIES[effectiveRole] as readonly string[]).includes(capability);
}
