apiVersion: v1
kind: Service
metadata:
  name: {{ include "managecallai.fullname" . }}-api
  labels:
    {{- include "managecallai.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "managecallai.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: 3000
      targetPort: http
