#!/usr/bin/env node
/**
 * Generates docs/api/openapi.yaml from the @managecallai/contracts Zod schemas.
 *
 * Strategy (hybrid):
 *   - Component schemas: generated from Zod via @asteasolutions/zod-to-openapi
 *   - Path definitions:  read from the existing openapi.yaml (kept as source of truth
 *                        for paths until SLICE-34 migrates them to code)
 *
 * Run:
 *   node scripts/generate-openapi.mjs
 *
 * Requires:
 *   pnpm --filter @managecallai/contracts build   (before first run)
 *   yaml (root devDependency)
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parse, stringify } from 'yaml';

// Importing contracts triggers the register.ts side-effect, populating the registry.
// OpenApiGeneratorV31 is re-exported from contracts to avoid a direct dep on @asteasolutions here.
import { registry, OpenApiGeneratorV31 } from '@managecallai/contracts';

const __dir = dirname(fileURLToPath(import.meta.url));
const specPath = join(__dir, '..', 'docs', 'api', 'openapi.yaml');

// ── 1. Read existing spec for paths, servers, tags, security ──────────────────
const existing = parse(readFileSync(specPath, 'utf8'));

// ── 2. Generate components from Zod registry ──────────────────────────────────
const description = [
  'REST API for the manageCallAI telecom control plane.',
  '',
  'Only implemented or intentionally exposed contract endpoints are documented here.',
  'Some foundational endpoints are early-availability but ready for integration testing.',
  'Runtime/internal endpoints are explicitly marked and require runtime-token authentication',
  '(`Authorization: Bearer <RUNTIME_API_TOKEN>` or `x-managecallai-runtime-token: <token>`).',
  '',
  '## Error responses',
  '',
  'All errors follow the RPC error standard:',
  '',
  '```json',
  '{ "error": "FAILED_PRECONDITION", "message": "Session is not running: completed", "request_id": "req-abc123" }',
  '```',
  '',
  'Clients must branch on `error` (machine-readable), never on `message` (may change).',
  '`request_id` is stable and matches the `x-request-id` response header for log correlation.',
  '',
  '| Code | HTTP | Meaning |',
  '|------|------|---------|',
  '| `NOT_FOUND` | 404 | Resource does not exist |',
  '| `INVALID_ARGUMENT` | 400 | Malformed request or validation failure |',
  '| `UNAUTHENTICATED` | 401 | Missing or invalid credential |',
  '| `PERMISSION_DENIED` | 403 | Credential valid but lacks permission |',
  '| `ALREADY_EXISTS` | 409 | Duplicate resource / unique-constraint violation |',
  '| `CONFLICT` | 409 | Generic conflict with no more precise cause |',
  '| `FAILED_PRECONDITION` | 409 | Resource exists but is in the wrong state for the action |',
  '| `RESOURCE_EXHAUSTED` | 429 | Rate limit exceeded |',
  '| `INTERNAL` | 500 | Unexpected server error |',
  '| `UNAVAILABLE` | 503 | Service temporarily unavailable |',
].join('\n');

const generator = new OpenApiGeneratorV31(registry.definitions);
const generated = generator.generateDocument({
  openapi: '3.1.0',
  info: {
    title: 'manageCallAI API',
    version: '0.1.0',
    summary: 'Business-level telecom control plane API over FreeSWITCH',
    description,
  },
});

// Merge: use existing paths + existing responses + generated schemas
const newSpec = {
  openapi: '3.1.0',
  info: existing.info,
  servers: existing.servers,
  tags: existing.tags,
  security: existing.security,
  paths: existing.paths,
  components: {
    ...existing.components,
    schemas: generated.components?.schemas ?? {},
  },
};

// ── 3. Write ──────────────────────────────────────────────────────────────────
const header =
  '# This file is GENERATED by scripts/generate-openapi.mjs\n' +
  '# Do not edit manually — edit packages/contracts/src/schemas/*.ts instead.\n' +
  '# To update: pnpm --filter @managecallai/contracts build && node scripts/generate-openapi.mjs\n\n';

writeFileSync(specPath, header + stringify(newSpec, { lineWidth: 120 }), 'utf8');

console.log(`Generated ${specPath}`);
console.log(`  schemas: ${Object.keys(newSpec.components?.schemas ?? {}).length} components`);
console.log(`  paths:   ${Object.keys(newSpec.paths ?? {}).length} path entries`);
