export const CAPABILITIES = {
  PLATFORM_TENANTS_VIEW: 'platform.tenants.view',
  PLATFORM_RUNTIME_VIEW: 'platform.runtime.view',
  PLATFORM_AUDIT_VIEW: 'platform.audit.view',

  TENANT_DASHBOARD_VIEW: 'tenant.dashboard.view',
  TENANT_EXTENSIONS_VIEW: 'tenant.extensions.view',
  TENANT_EXTENSIONS_CREATE: 'tenant.extensions.create',
  TENANT_EXTENSIONS_UPDATE: 'tenant.extensions.update',
  TENANT_EXTENSIONS_DEACTIVATE: 'tenant.extensions.deactivate',
  TENANT_CALLS_VIEW: 'tenant.calls.view',
  TENANT_DIRECTORY_SMOKE_TEST: 'tenant.directory_smoke_test.run',

  TENANT_PHONE_NUMBERS_VIEW: 'tenant.phone_numbers.view',
  TENANT_PHONE_NUMBERS_CREATE: 'tenant.phone_numbers.create',
  TENANT_PHONE_NUMBERS_UPDATE: 'tenant.phone_numbers.update',
  TENANT_PHONE_NUMBERS_DEACTIVATE: 'tenant.phone_numbers.deactivate',

  TENANT_INBOUND_ROUTES_VIEW: 'tenant.inbound_routes.view',
  TENANT_INBOUND_ROUTES_CREATE: 'tenant.inbound_routes.create',
  TENANT_INBOUND_ROUTES_UPDATE: 'tenant.inbound_routes.update',
  TENANT_INBOUND_ROUTES_ACTIVATE: 'tenant.inbound_routes.activate',
  TENANT_INBOUND_ROUTES_DEACTIVATE: 'tenant.inbound_routes.deactivate',
  TENANT_INBOUND_ROUTES_TEST: 'tenant.inbound_routes.test',

  TENANT_PROMPTS_VIEW: 'tenant.prompts.view',
  TENANT_PROMPTS_CREATE: 'tenant.prompts.create',
  TENANT_PROMPTS_UPDATE: 'tenant.prompts.update',
  TENANT_PROMPTS_DEACTIVATE: 'tenant.prompts.deactivate',

  TENANT_IVR_FLOWS_VIEW: 'tenant.ivr_flows.view',
  TENANT_IVR_FLOWS_CREATE: 'tenant.ivr_flows.create',
  TENANT_IVR_FLOWS_UPDATE: 'tenant.ivr_flows.update',
  TENANT_IVR_FLOWS_VALIDATE: 'tenant.ivr_flows.validate',
  TENANT_IVR_FLOWS_SIMULATE: 'tenant.ivr_flows.simulate',
  TENANT_IVR_FLOWS_PUBLISH: 'tenant.ivr_flows.publish',
  TENANT_IVR_FLOWS_ROLLBACK: 'tenant.ivr_flows.rollback',

  TENANT_APPROVALS_VIEW: 'tenant.approvals.view',
  TENANT_APPROVALS_DECIDE: 'tenant.approvals.decide',
} as const;

export type Capability = (typeof CAPABILITIES)[keyof typeof CAPABILITIES];

export type Role = 'platform_admin' | 'tenant_admin';

const TENANT_CAPABILITIES: readonly Capability[] = [
  CAPABILITIES.TENANT_DASHBOARD_VIEW,
  CAPABILITIES.TENANT_EXTENSIONS_VIEW,
  CAPABILITIES.TENANT_EXTENSIONS_CREATE,
  CAPABILITIES.TENANT_EXTENSIONS_UPDATE,
  CAPABILITIES.TENANT_EXTENSIONS_DEACTIVATE,
  CAPABILITIES.TENANT_CALLS_VIEW,
  CAPABILITIES.TENANT_DIRECTORY_SMOKE_TEST,
  CAPABILITIES.TENANT_PHONE_NUMBERS_VIEW,
  CAPABILITIES.TENANT_PHONE_NUMBERS_CREATE,
  CAPABILITIES.TENANT_PHONE_NUMBERS_UPDATE,
  CAPABILITIES.TENANT_PHONE_NUMBERS_DEACTIVATE,
  CAPABILITIES.TENANT_INBOUND_ROUTES_VIEW,
  CAPABILITIES.TENANT_INBOUND_ROUTES_CREATE,
  CAPABILITIES.TENANT_INBOUND_ROUTES_UPDATE,
  CAPABILITIES.TENANT_INBOUND_ROUTES_ACTIVATE,
  CAPABILITIES.TENANT_INBOUND_ROUTES_DEACTIVATE,
  CAPABILITIES.TENANT_INBOUND_ROUTES_TEST,
  CAPABILITIES.TENANT_PROMPTS_VIEW,
  CAPABILITIES.TENANT_PROMPTS_CREATE,
  CAPABILITIES.TENANT_PROMPTS_UPDATE,
  CAPABILITIES.TENANT_PROMPTS_DEACTIVATE,
  CAPABILITIES.TENANT_IVR_FLOWS_VIEW,
  CAPABILITIES.TENANT_IVR_FLOWS_CREATE,
  CAPABILITIES.TENANT_IVR_FLOWS_UPDATE,
  CAPABILITIES.TENANT_IVR_FLOWS_VALIDATE,
  CAPABILITIES.TENANT_IVR_FLOWS_SIMULATE,
  CAPABILITIES.TENANT_IVR_FLOWS_PUBLISH,
  CAPABILITIES.TENANT_IVR_FLOWS_ROLLBACK,
  CAPABILITIES.TENANT_APPROVALS_VIEW,
  CAPABILITIES.TENANT_APPROVALS_DECIDE,
];

const ROLE_CAPABILITIES: Record<Role, readonly Capability[]> = {
  platform_admin: [
    CAPABILITIES.PLATFORM_TENANTS_VIEW,
    CAPABILITIES.PLATFORM_RUNTIME_VIEW,
    CAPABILITIES.PLATFORM_AUDIT_VIEW,
    ...TENANT_CAPABILITIES,
  ],
  tenant_admin: TENANT_CAPABILITIES,
};

export function hasCapability(role: Role | undefined, capability: Capability): boolean {
  const effectiveRole: Role = role ?? 'tenant_admin';
  return (ROLE_CAPABILITIES[effectiveRole] as readonly string[]).includes(capability);
}
