export const CAPABILITIES = {
  PLATFORM_TENANTS_VIEW: 'platform.tenants.view',
  PLATFORM_RUNTIME_VIEW: 'platform.runtime.view',
  PLATFORM_AUDIT_VIEW: 'platform.audit.view',

  TENANT_DASHBOARD_VIEW: 'tenant.dashboard.view',
  TENANT_EXTENSIONS_VIEW: 'tenant.extensions.view',
  TENANT_EXTENSIONS_CREATE: 'tenant.extensions.create',
  TENANT_EXTENSIONS_UPDATE: 'tenant.extensions.update',
  TENANT_EXTENSIONS_DEACTIVATE: 'tenant.extensions.deactivate',
  TENANT_CALLS_VIEW: 'tenant.calls.view',
  TENANT_DIRECTORY_SMOKE_TEST: 'tenant.directory_smoke_test.run',

  TENANT_PHONE_NUMBERS_VIEW: 'tenant.phone_numbers.view',
  TENANT_PHONE_NUMBERS_CREATE: 'tenant.phone_numbers.create',
  TENANT_PHONE_NUMBERS_UPDATE: 'tenant.phone_numbers.update',
  TENANT_PHONE_NUMBERS_DEACTIVATE: 'tenant.phone_numbers.deactivate',

  TENANT_INBOUND_ROUTES_VIEW: 'tenant.inbound_routes.view',
  TENANT_INBOUND_ROUTES_CREATE: 'tenant.inbound_routes.create',
  TENANT_INBOUND_ROUTES_UPDATE: 'tenant.inbound_routes.update',
  TENANT_INBOUND_ROUTES_ACTIVATE: 'tenant.inbound_routes.activate',
  TENANT_INBOUND_ROUTES_DEACTIVATE: 'tenant.inbound_routes.deactivate',
  TENANT_INBOUND_ROUTES_TEST: 'tenant.inbound_routes.test',

  TENANT_PROMPTS_VIEW: 'tenant.prompts.view',
  TENANT_PROMPTS_CREATE: 'tenant.prompts.create',
  TENANT_PROMPTS_UPDATE: 'tenant.prompts.update',
  TENANT_PROMPTS_DEACTIVATE: 'tenant.prompts.deactivate',

  TENANT_IVR_FLOWS_VIEW: 'tenant.ivr_flows.view',
  TENANT_IVR_FLOWS_CREATE: 'tenant.ivr_flows.create',
  TENANT_IVR_FLOWS_UPDATE: 'tenant.ivr_flows.update',
  TENANT_IVR_FLOWS_VALIDATE: 'tenant.ivr_flows.validate',
  TENANT_IVR_FLOWS_SIMULATE: 'tenant.ivr_flows.simulate',
  TENANT_IVR_FLOWS_PUBLISH: 'tenant.ivr_flows.publish',
  TENANT_IVR_FLOWS_ROLLBACK: 'tenant.ivr_flows.rollback',

  TENANT_APPROVALS_VIEW: 'tenant.approvals.view',
  TENANT_APPROVALS_DECIDE: 'tenant.approvals.decide',

  TENANT_CALL_GROUPS_VIEW: 'tenant.call_groups.view',
  TENANT_CALL_GROUPS_CREATE: 'tenant.call_groups.create',
  TENANT_CALL_GROUPS_UPDATE: 'tenant.call_groups.update',
  TENANT_CALL_GROUPS_DEACTIVATE: 'tenant.call_groups.deactivate',

  TENANT_QUEUES_VIEW: 'tenant.queues.view',
  TENANT_QUEUES_CREATE: 'tenant.queues.create',
  TENANT_QUEUES_UPDATE: 'tenant.queues.update',
  TENANT_QUEUES_DEACTIVATE: 'tenant.queues.deactivate',

  TENANT_VOICEMAIL_BOXES_VIEW: 'tenant.voicemail_boxes.view',
  TENANT_VOICEMAIL_BOXES_CREATE: 'tenant.voicemail_boxes.create',
  TENANT_VOICEMAIL_BOXES_UPDATE: 'tenant.voicemail_boxes.update',
  TENANT_VOICEMAIL_BOXES_DEACTIVATE: 'tenant.voicemail_boxes.deactivate',

  TENANT_AUTOMATION_KEYS_VIEW: 'tenant.automation.keys.view',
  TENANT_AUTOMATION_KEYS_MANAGE: 'tenant.automation.keys.manage',
  TENANT_AUTOMATION_WEBHOOKS_VIEW: 'tenant.automation.webhooks.view',
  TENANT_AUTOMATION_WEBHOOKS_MANAGE: 'tenant.automation.webhooks.manage',

  TENANT_SCHEDULES_VIEW: 'tenant.schedules.view',
  TENANT_SCHEDULES_CREATE: 'tenant.schedules.create',
  TENANT_SCHEDULES_UPDATE: 'tenant.schedules.update',

  TENANT_CONFERENCE_ROOMS_VIEW: 'tenant.conference_rooms.view',
  TENANT_CONFERENCE_ROOMS_CREATE: 'tenant.conference_rooms.create',
  TENANT_CONFERENCE_ROOMS_UPDATE: 'tenant.conference_rooms.update',
  TENANT_CONFERENCE_ROOMS_DEACTIVATE: 'tenant.conference_rooms.deactivate',

  TENANT_FEATURE_CODES_VIEW: 'tenant.feature_codes.view',
  TENANT_FEATURE_CODES_CREATE: 'tenant.feature_codes.create',
  TENANT_FEATURE_CODES_UPDATE: 'tenant.feature_codes.update',
  TENANT_FEATURE_CODES_VALIDATE: 'tenant.feature_codes.validate',
  TENANT_FEATURE_CODES_PUBLISH: 'tenant.feature_codes.publish',
  TENANT_FEATURE_CODES_DEACTIVATE: 'tenant.feature_codes.deactivate',

  TENANT_OUTBOUND_ROUTES_VIEW: 'tenant.outbound_routes.view',
  TENANT_OUTBOUND_ROUTES_CREATE: 'tenant.outbound_routes.create',
  TENANT_OUTBOUND_ROUTES_UPDATE: 'tenant.outbound_routes.update',

  TENANT_OUTBOUND_CALLS_CREATE: 'tenant.outbound_calls.create',
  TENANT_OUTBOUND_CALLS_VIEW: 'tenant.outbound_calls.view',

  TENANT_CHANNEL_ACCOUNTS_VIEW: 'tenant.channel_accounts.view',
  TENANT_CHANNEL_ACCOUNTS_MANAGE: 'tenant.channel_accounts.manage',
  TENANT_CHANNEL_MESSAGES_VIEW: 'tenant.channel_messages.view',
  TENANT_CHANNEL_MESSAGES_SEND: 'tenant.channel_messages.send',
  TENANT_MEETING_SESSIONS_VIEW: 'tenant.meeting_sessions.view',
  TENANT_MEETING_SESSIONS_MANAGE: 'tenant.meeting_sessions.manage',

  TENANT_AUDIT_LOG_VIEW: 'tenant.audit_log.view',

  TENANT_RECORDINGS_VIEW: 'tenant.recordings.view',
  TENANT_EXPORT_RUN: 'tenant.export.run',

  TENANT_USERS_VIEW: 'tenant.users.view',
  TENANT_USERS_MANAGE: 'tenant.users.manage',

  // SLICE-47: recording retention and privacy
  TENANT_COMPLIANCE_ADMIN: 'tenant.compliance.admin',

  // SLICE-48: security alert rules
  TENANT_SECURITY_ALERTS_VIEW: 'tenant.security.alerts.view',
  TENANT_SECURITY_ALERTS_MANAGE: 'tenant.security.alerts.manage',

  // SLICE-45: telecom fraud policy
  TENANT_FRAUD_POLICY_VIEW: 'tenant.fraud_policy.view',
  TENANT_FRAUD_POLICY_MANAGE: 'tenant.fraud_policy.manage',

  // v0.6: AI-assisted advisory risk analysis (read-only, advisory only)
  TENANT_RISK_ANALYSIS: 'tenant.risk_analysis.run',

  // v0.6: natural-language telecom reporting (read-only, bounded queries only)
  TENANT_NL_REPORTING: 'tenant.reporting.nl_query',

  // v0.6: AI-assisted call failure explanation (read-only, advisory only)
  TENANT_CALL_FAILURE_EXPLAIN: 'tenant.calls.explain_failure',

  // v0.6.1: provider-backed AI policy and gated provider use
  TENANT_AI_POLICY_VIEW: 'tenant.ai.policy.view',
  TENANT_AI_POLICY_MANAGE: 'tenant.ai.policy.manage',
  TENANT_AI_PROVIDER_BACKED_USE: 'tenant.ai.provider_backed.use',

  // v0.7.0 contact-center: agent workspace (#271), availability (#272), skills (#273)
  TENANT_AGENT_PROFILES_VIEW: 'tenant.agents.profiles.view',
  TENANT_AGENT_PROFILES_MANAGE: 'tenant.agents.profiles.manage',
  TENANT_AGENT_AVAILABILITY_VIEW: 'tenant.agents.availability.view',
  TENANT_AGENT_AVAILABILITY_SET: 'tenant.agents.availability.set',
  TENANT_AGENT_WORKSPACE_VIEW: 'tenant.agents.workspace.view',
  TENANT_SKILLS_VIEW: 'tenant.skills.view',
  TENANT_SKILLS_MANAGE: 'tenant.skills.manage',
  TENANT_ROUTING_EVALUATE: 'tenant.routing.evaluate',

  // v0.7.0 contact-center: CRM screen-pop (#281), campaigns (#282)
  TENANT_CRM_INTEGRATIONS_VIEW: 'tenant.crm.integrations.view',
  TENANT_CRM_INTEGRATIONS_MANAGE: 'tenant.crm.integrations.manage',
  TENANT_CRM_LOOKUP: 'tenant.crm.lookup',
  TENANT_CAMPAIGNS_VIEW: 'tenant.campaigns.view',
  TENANT_CAMPAIGNS_MANAGE: 'tenant.campaigns.manage',
  TENANT_CAMPAIGNS_CONTACTS_MANAGE: 'tenant.campaigns.contacts.manage',

  // v0.7.0 contact-center: supervisor dashboard (#274), monitor/whisper/barge (#275),
  //   queue callbacks (#276), SLA tracking and wallboards (#277)
  TENANT_SUPERVISOR_DASHBOARD_VIEW: 'tenant.supervisor.dashboard.view',
  TENANT_SUPERVISOR_CONTROLS_VIEW: 'tenant.supervisor.controls.view',
  TENANT_SUPERVISOR_CONTROLS_MANAGE: 'tenant.supervisor.controls.manage',
  TENANT_QUEUE_CALLBACKS_VIEW: 'tenant.queue_callbacks.view',
  TENANT_QUEUE_CALLBACKS_MANAGE: 'tenant.queue_callbacks.manage',
} as const;

export type Capability = (typeof CAPABILITIES)[keyof typeof CAPABILITIES];

export type Role = 'platform_admin' | 'tenant_admin' | 'tenant_operator' | 'tenant_viewer' | 'end_user' | 'agent';

const TENANT_VIEW_CAPABILITIES: readonly Capability[] = [
  CAPABILITIES.TENANT_DASHBOARD_VIEW,
  CAPABILITIES.TENANT_EXTENSIONS_VIEW,
  CAPABILITIES.TENANT_CALLS_VIEW,
  CAPABILITIES.TENANT_RECORDINGS_VIEW,
  CAPABILITIES.TENANT_PHONE_NUMBERS_VIEW,
  CAPABILITIES.TENANT_INBOUND_ROUTES_VIEW,
  CAPABILITIES.TENANT_PROMPTS_VIEW,
  CAPABILITIES.TENANT_IVR_FLOWS_VIEW,
  CAPABILITIES.TENANT_APPROVALS_VIEW,
  CAPABILITIES.TENANT_CALL_GROUPS_VIEW,
  CAPABILITIES.TENANT_QUEUES_VIEW,
  CAPABILITIES.TENANT_VOICEMAIL_BOXES_VIEW,
  CAPABILITIES.TENANT_AUTOMATION_KEYS_VIEW,
  CAPABILITIES.TENANT_AUTOMATION_WEBHOOKS_VIEW,
  CAPABILITIES.TENANT_SCHEDULES_VIEW,
  CAPABILITIES.TENANT_CONFERENCE_ROOMS_VIEW,
  CAPABILITIES.TENANT_FEATURE_CODES_VIEW,
  CAPABILITIES.TENANT_OUTBOUND_ROUTES_VIEW,
  CAPABILITIES.TENANT_OUTBOUND_CALLS_VIEW,
  CAPABILITIES.TENANT_CHANNEL_ACCOUNTS_VIEW,
  CAPABILITIES.TENANT_CHANNEL_MESSAGES_VIEW,
  CAPABILITIES.TENANT_MEETING_SESSIONS_VIEW,
  CAPABILITIES.TENANT_AI_POLICY_VIEW,
  CAPABILITIES.TENANT_AGENT_PROFILES_VIEW,
  CAPABILITIES.TENANT_AGENT_AVAILABILITY_VIEW,
  CAPABILITIES.TENANT_SKILLS_VIEW,
  CAPABILITIES.TENANT_CRM_INTEGRATIONS_VIEW,
  CAPABILITIES.TENANT_CAMPAIGNS_VIEW,
  CAPABILITIES.TENANT_SUPERVISOR_DASHBOARD_VIEW,
  CAPABILITIES.TENANT_SUPERVISOR_CONTROLS_VIEW,
  CAPABILITIES.TENANT_QUEUE_CALLBACKS_VIEW,
];

const TENANT_OPERATOR_CAPABILITIES: readonly Capability[] = [
  ...TENANT_VIEW_CAPABILITIES,
  CAPABILITIES.TENANT_AUDIT_LOG_VIEW,
  CAPABILITIES.TENANT_EXPORT_RUN,
  CAPABILITIES.TENANT_USERS_VIEW,
  CAPABILITIES.TENANT_SECURITY_ALERTS_VIEW,
  CAPABILITIES.TENANT_FRAUD_POLICY_VIEW,
  CAPABILITIES.TENANT_DIRECTORY_SMOKE_TEST,
  CAPABILITIES.TENANT_EXTENSIONS_CREATE,
  CAPABILITIES.TENANT_EXTENSIONS_UPDATE,
  CAPABILITIES.TENANT_PHONE_NUMBERS_CREATE,
  CAPABILITIES.TENANT_PHONE_NUMBERS_UPDATE,
  CAPABILITIES.TENANT_INBOUND_ROUTES_CREATE,
  CAPABILITIES.TENANT_INBOUND_ROUTES_UPDATE,
  CAPABILITIES.TENANT_INBOUND_ROUTES_ACTIVATE,
  CAPABILITIES.TENANT_INBOUND_ROUTES_TEST,
  CAPABILITIES.TENANT_PROMPTS_CREATE,
  CAPABILITIES.TENANT_PROMPTS_UPDATE,
  CAPABILITIES.TENANT_IVR_FLOWS_CREATE,
  CAPABILITIES.TENANT_IVR_FLOWS_UPDATE,
  CAPABILITIES.TENANT_IVR_FLOWS_VALIDATE,
  CAPABILITIES.TENANT_IVR_FLOWS_SIMULATE,
  CAPABILITIES.TENANT_CALL_GROUPS_CREATE,
  CAPABILITIES.TENANT_CALL_GROUPS_UPDATE,
  CAPABILITIES.TENANT_QUEUES_CREATE,
  CAPABILITIES.TENANT_QUEUES_UPDATE,
  CAPABILITIES.TENANT_VOICEMAIL_BOXES_CREATE,
  CAPABILITIES.TENANT_VOICEMAIL_BOXES_UPDATE,
  CAPABILITIES.TENANT_SCHEDULES_CREATE,
  CAPABILITIES.TENANT_SCHEDULES_UPDATE,
  CAPABILITIES.TENANT_CONFERENCE_ROOMS_CREATE,
  CAPABILITIES.TENANT_CONFERENCE_ROOMS_UPDATE,
  CAPABILITIES.TENANT_FEATURE_CODES_CREATE,
  CAPABILITIES.TENANT_FEATURE_CODES_UPDATE,
  CAPABILITIES.TENANT_FEATURE_CODES_VALIDATE,
  CAPABILITIES.TENANT_OUTBOUND_ROUTES_CREATE,
  CAPABILITIES.TENANT_OUTBOUND_ROUTES_UPDATE,
  CAPABILITIES.TENANT_OUTBOUND_CALLS_CREATE,
  CAPABILITIES.TENANT_CHANNEL_ACCOUNTS_MANAGE,
  CAPABILITIES.TENANT_CHANNEL_MESSAGES_SEND,
  CAPABILITIES.TENANT_MEETING_SESSIONS_MANAGE,
  CAPABILITIES.TENANT_RISK_ANALYSIS,
  CAPABILITIES.TENANT_NL_REPORTING,
  CAPABILITIES.TENANT_CALL_FAILURE_EXPLAIN,
  CAPABILITIES.TENANT_AI_PROVIDER_BACKED_USE,
  CAPABILITIES.TENANT_ROUTING_EVALUATE,
  CAPABILITIES.TENANT_CRM_LOOKUP,
  CAPABILITIES.TENANT_CAMPAIGNS_CONTACTS_MANAGE,
  CAPABILITIES.TENANT_SUPERVISOR_CONTROLS_MANAGE,
  CAPABILITIES.TENANT_QUEUE_CALLBACKS_MANAGE,
];

const TENANT_CAPABILITIES: readonly Capability[] = [
  ...TENANT_OPERATOR_CAPABILITIES,
  CAPABILITIES.TENANT_EXTENSIONS_DEACTIVATE,
  CAPABILITIES.TENANT_PHONE_NUMBERS_DEACTIVATE,
  CAPABILITIES.TENANT_INBOUND_ROUTES_DEACTIVATE,
  CAPABILITIES.TENANT_PROMPTS_DEACTIVATE,
  CAPABILITIES.TENANT_IVR_FLOWS_PUBLISH,
  CAPABILITIES.TENANT_IVR_FLOWS_ROLLBACK,
  CAPABILITIES.TENANT_APPROVALS_DECIDE,
  CAPABILITIES.TENANT_CALL_GROUPS_DEACTIVATE,
  CAPABILITIES.TENANT_QUEUES_DEACTIVATE,
  CAPABILITIES.TENANT_VOICEMAIL_BOXES_DEACTIVATE,
  CAPABILITIES.TENANT_AUTOMATION_KEYS_MANAGE,
  CAPABILITIES.TENANT_AUTOMATION_WEBHOOKS_MANAGE,
  CAPABILITIES.TENANT_CONFERENCE_ROOMS_DEACTIVATE,
  CAPABILITIES.TENANT_FEATURE_CODES_PUBLISH,
  CAPABILITIES.TENANT_FEATURE_CODES_DEACTIVATE,
  CAPABILITIES.TENANT_USERS_MANAGE,
  CAPABILITIES.TENANT_COMPLIANCE_ADMIN,
  CAPABILITIES.TENANT_SECURITY_ALERTS_MANAGE,
  CAPABILITIES.TENANT_FRAUD_POLICY_MANAGE,
  CAPABILITIES.TENANT_AI_POLICY_MANAGE,
  CAPABILITIES.TENANT_AGENT_PROFILES_MANAGE,
  CAPABILITIES.TENANT_SKILLS_MANAGE,
  CAPABILITIES.TENANT_CRM_INTEGRATIONS_MANAGE,
  CAPABILITIES.TENANT_CAMPAIGNS_MANAGE,
  CAPABILITIES.TENANT_SUPERVISOR_CONTROLS_MANAGE,
  CAPABILITIES.TENANT_QUEUE_CALLBACKS_MANAGE,
];

const ROLE_CAPABILITIES: Record<Role, readonly Capability[]> = {
  platform_admin: [
    CAPABILITIES.PLATFORM_TENANTS_VIEW,
    CAPABILITIES.PLATFORM_RUNTIME_VIEW,
    CAPABILITIES.PLATFORM_AUDIT_VIEW,
    ...TENANT_CAPABILITIES,
  ],
  tenant_admin: TENANT_CAPABILITIES,
  tenant_operator: TENANT_OPERATOR_CAPABILITIES,
  tenant_viewer: TENANT_VIEW_CAPABILITIES,
  end_user: [],
  agent: [
    CAPABILITIES.TENANT_AGENT_WORKSPACE_VIEW,
    CAPABILITIES.TENANT_AGENT_AVAILABILITY_SET,
    CAPABILITIES.TENANT_QUEUES_VIEW,
    CAPABILITIES.TENANT_EXTENSIONS_VIEW,
  ],
};

export function hasCapability(role: Role | string | undefined, capability: Capability): boolean {
  if (!role || !(role in ROLE_CAPABILITIES)) return false;
  return (ROLE_CAPABILITIES[role as Role] as readonly string[]).includes(capability);
}
